// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDefaultPaths() {
  return window['go']['main']['App']['GetDefaultPaths']();
}

export function GetUpgradeNotice() {
  return window['go']['main']['App']['GetUpgradeNotice']();
}

export function Install(arg1) {
  return window['go']['main']['App']['Install'](arg1);
}

export function IsInstalled() {
  return window['go']['main']['App']['IsInstalled']();
}

export function PickDirectory() {
  return window['go']['main']['App']['PickDirectory']();
}

export function Uninstall() {
  return window['go']['main']['App']['Uninstall']();
}
