// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDefaultPaths():Promise<Record<string, string>>;

export function GetUpgradeNotice():Promise<Record<string, any>>;

export function Install(arg1:string):Promise<Record<string, any>>;

export function IsInstalled():Promise<boolean>;

export function PickDirectory():Promise<string>;

export function Uninstall():Promise<Record<string, any>>;
